### ISSUE TITLE
Fix issue with multi transformers

### ISSUE THREAD

**Issue by ppnaik1890** [observ-vol-mgt/observ-vol-mgt#175]
When using multiple transform are added to a processor, all metrics are getting dropped. 
e.g. yaml that is throwing this error
```
processors:
  - type: drop
    id: drop_1
    metrics:
      metric_name: nwdaf_5G_network_utilization
      condition: cluster=c0 and instance=metricgen1:8000
  - type: frequency
    id: freq_1
    metrics:
      metric_name: process_cpu_seconds_total
      interval: 10000
      condition: cluster=$cluster and instance=metricgen1:8000
dag:
  - node: drop_1
    children: []
  - node: freq_1
    children: []

```
